//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleIntrestApi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intrest
    {
        public int id { get; set; }
        public Nullable<double> principle { get; set; }
        public Nullable<double> rate { get; set; }
        public Nullable<double> samay { get; set; }
    }
}
